### ISSUE TITLE
Oil prospecting data is missing and oil drilling rig places pipe and stops

### ISSUE THREAD

**Issue by bear989** [Blood-Asp/GT5-Unofficial#1108]
this was tested on 2 seperate servers and SSP with to diffrent packs both on the latest update.
https://youtu.be/OCYTaI2kqbw

**Comment by SapientMC** [comment]
I can confirm this bug. Prospected Oil, pumped in v29 lost.
I don't know what and what for was changed in Oil generation algorithm, but it should not brake already created worlds.

**Comment by Blood-Asp** [comment]
i did just release .31pre build with an fix. try testing that. it could also be that the generation algorithm changed, so the places to find oil changed.

**Comment by SapientMC** [comment]
@Blood-Asp I saw it. And do not see any way i can agree with "places to find oil changed".
I've already made all infrastructure to rich source (Offshore Platform, Drills, Tank, Railway, Rail stations and so on) and can not move it anywhere.

**Comment by Blood-Asp** [comment]
Once oil got prospected, it gets stored and should be save. But all that is not prospeced might be moved as the generation algorithm changed in .29 or .30
That means the other chunks in the 6x6 area might now differ.

**Comment by SapientMC** [comment]
What if it was prospected by Advanced Prospector. Does it man every chunk are prospected?

**Comment by draknyte1** [comment]
Why not roll back the changes made to oil generation? So that people don't have to move their shit to new 'optimal' mining locations.

**Comment by mura3277** [comment]
@Blood-Asp This was fixed correct?

**Comment by Blood-Asp** [comment]
Imho yes, but there is still one change that happend a while back and no one complained for a long time. Now i'm not sure if even that change (.29 afaik) should be reverted or we now just accept it as it is now. The main issue is fixed at last.

**Comment by SapientMC** [comment]
@Muramasa- Ill check it after on v31. Hope type and amount of drilling oil will not change from v29.

**Comment by SapientMC** [comment]
@Muramasa- Its still broken in 31pre3.
v29. Heavy Oil source with pump speed 432L per operation
v31pre3 It changes to 279L of Natural Gas.
back to v29 its still Natural Gas but at twice speed: 548L

Please leave old algorithm, at lease for existing worlds.
PS I can give you save for testing.

**Comment by Blood-Asp** [comment]
It is fixed as much as possible... Some internal changes make it impossible to return to the exact old values.
