### ISSUE TITLE
Broken steam machines

### ISSUE THREAD

**Issue by DEMOOH** [Blood-Asp/GT5-Unofficial#879]
Affected steam machines don't have recipies.
https://github.com/Blood-Asp/GT5-Unofficial/commit/5c5aad452228255815deab8ff3bcb85e147ef63b

**Comment by mura3277** [comment]
Should be fixed by 65c5813

**Comment by DEMOOH** [comment]
I see, this may (should) be closed now.

**Comment by mura3277** [comment]
Whoops linked wrong commit. Should be fixed by 37ca674

**Comment by DEMOOH** [comment]
Yeah, i figured this out.

**Comment by YuRaNnNzZZ** [comment]
Bronze Extractor and Bronze Compressor still not working.
EDIT: High Pressure ones doesn't work too.

**Comment by Techlone** [comment]
http://nooooooooooooooo.com/

**Comment by DEMOOH** [comment]
Yeah, recipe processing is more complex than it seems. While ic2 recipies handling is similar to vanilla 
(see steam furnaces 
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/tileentities/machines/steam/GT_MetaTileEntity_Furnace_Bronze.java) 
all other machines handle those differently.
(forge hammer https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/tileentities/machines/steam/GT_MetaTileEntity_ForgeHammer_Bronze.java 
alloy smelter https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/tileentities/machines/steam/GT_MetaTileEntity_AlloySmelter_Bronze.java )

And macerator works, extractor and compressor are broken for sure.

**Comment by draknyte1** [comment]
Either this or https://github.com/Blood-Asp/GT5-Unofficial/commit/37ca6746e3f543f6595ccee7e8b07cd08b4cecba breaks steam extractor of raw rubber dust, preventing players from even making LV machines. Good fucking work on the testing guys. broken in 28pre2, works fine in .27 and I think .28pre1.

**Comment by leagris** [comment]
Steam Compressor also broke
I duplicated here: https://github.com/Blood-Asp/GT5-Unofficial/issues/886

Referred here for BeyondReality ModPack https://github.com/Beyond-Reality/BeyondRealityModPack/issues/445

Rollback to 5.09.28pre restore Steam Machines.

**Comment by DEMOOH** [comment]
#887
