### ISSUE TITLE
[1.10.2] Crash with rftools builder quarry mode

### ISSUE THREAD

**Issue by SiblisCu** [Blood-Asp/GT5-Unofficial#994]
The game crash to desktop  every time I load the world.
This happens while quarring the overworld.

Crash report:

[20:29:25] [Client thread/INFO] [STDOUT/]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  IvToolkit (IvToolkit-1.3.2.1-1.10.jar)
  ForgelinPlugin (Forgelin-1.4.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  IC2core (industrialcraft-2-2.6.142-ex110.jar)
  CorePlugin (MrTJPCore-1.10.2-2.0.0.14-universal.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.0.155-universal.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.2-alpha-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.201-universal.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.13r.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta2-anarchy.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.5.136-universal.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.8.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 3/24/17 8:29 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at gregtech.common.blocks.GT_Block_GeneratedOres.getDrops(GT_Block_GeneratedOres.java:276)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.quarryBlock(BuilderTileEntity.java:1157)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.handleSingleBlock(BuilderTileEntity.java:959)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.handleBlockShaped(BuilderTileEntity.java:864)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.checkStateServerShaped(BuilderTileEntity.java:624)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.checkStateServer(BuilderTileEntity.java:656)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.func_73660_a(BuilderTileEntity.java:638)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at gregtech.common.blocks.GT_Block_GeneratedOres.getDrops(GT_Block_GeneratedOres.java:276)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.quarryBlock(BuilderTileEntity.java:1157)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.handleSingleBlock(BuilderTileEntity.java:959)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.handleBlockShaped(BuilderTileEntity.java:864)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.checkStateServerShaped(BuilderTileEntity.java:624)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.checkStateServer(BuilderTileEntity.java:656)
	at mcjty.rftools.blocks.builder.BuilderTileEntity.func_73660_a(BuilderTileEntity.java:638)

-- Block entity being ticked --
Details:
	Name: rftools_builder // mcjty.rftools.blocks.builder.BuilderTileEntity
	Block type: ID #3295 (tile.rftools.builder // mcjty.rftools.blocks.builder.BuilderBlock)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-122,71,255), Chunk: (at 6,4,15 in -8,15; contains blocks -128,0,240 to -113,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #3295 (tile.rftools.builder // mcjty.rftools.blocks.builder.BuilderBlock)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: Betond infinity
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 628 Drop: 0
	Level seed: 802002880
	Level generator: ID 04 - customized, ver 0. Features enabled: true
	Level generator options: {"coordinateScale":684.412,"heightScale":684.412,"lowerLimitScale":512.0,"upperLimitScale":512.0,"depthNoiseScaleX":200.0,"depthNoiseScaleZ":200.0,"depthNoiseScaleExponent":0.5,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"baseSize":8.5,"stretchY":12.0,"biomeDepthWeight":1.0,"biomeDepthOffset":0.0,"biomeScaleWeight":1.0,"biomeScaleOffset":0.0,"seaLevel":63,"useCaves":true,"useDungeons":true,"dungeonChance":100,"useStrongholds":true,"useVillages":true,"useMineShafts":true,"useTemples":true,"useMonuments":true,"useRavines":true,"useWaterLakes":true,"waterLakeChance":4,"useLavaLakes":true,"lavaLakeChance":60,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":4,"riverSize":4,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":80,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":80,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":80,"coalSize":17,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":128,"ironSize":14,"ironCount":20,"ironMinHeight":0,"ironMaxHeight":64,"goldSize":9,"goldCount":2,"goldMinHeight":0,"goldMaxHeight":32,"redstoneSize":8,"redstoneCount":8,"redstoneMinHeight":0,"redstoneMaxHeight":16,"diamondSize":8,"diamondCount":1,"diamondMinHeight":0,"diamondMaxHeight":16,"lapisSize":7,"lapisCount":1,"lapisCenterHeight":16,"lapisSpread":16}
	Level spawn location: World: (-208,64,256), Chunk: (at 0,4,0 in -13,16; contains blocks -208,0,256 to -193,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3207229 game time, 3507780 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 89383 (now: false), thunder time: 81090 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.4.0-67-generic
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7890744240 bytes (7525 MB) / 11139022848 bytes (10623 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 2 total; -Xms6144m -Xmx12288m
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 210 mods loaded, 210 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	ivtoolkit{1.3.2.1-1.10} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{2.1.3.201} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.201-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.2.7} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCHIJAAAA	cofhcore{4.1.0} [CoFH Core] (CoFHCore-1.10.2-4.1.0.155-universal.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r105} [Actually Additions] (ActuallyAdditions-1.10.2-r105.jar) 
	UCHIJAAAA	IC2{2.6.142-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.142-ex110.jar) 
	UCHIJAAAA	advanced_machines{60.0.1} [Advanced Machines] (Advanced Machines-60.0.1.jar) 
	UCHIJAAAA	advanced_solar_panels{4.0.4} [Advanced Solar Panels] (Advanced Solar Panels-4.0.4.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-11.jar) 
	UCHIJAAAA	bdlib{1.12.4.24} [BD Lib] (bdlib-1.12.4.24-mc1.10.2.jar) 
	UCHIJAAAA	ae2stuff{0.6.0.9} [AE2 Stuff] (ae2stuff-0.6.0.9-mc1.10.2.jar) 
	UCHIJAAAA	infinitylib{1.10.2-0.7.0} [InfinityLib] (infinitylib-0.7.0.jar) 
	UCHIJAAAA	agricraft{2.0.0-0.7.0-a12} [AgriCraft] (agricraft-2.0.0-0.7.0-a12.jar) 
	UCHIJAAAA	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJAAAA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCHIJAAAA	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCHIJAAAA	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCHIJAAAA	aquaculture{1.4.0} [Aquaculture] (Aquaculture-1.10.2-1.4.0.28.jar) 
	UCHIJAAAA	architecturecraft{1.7.1} [ArchitectureCraft] (ArchitectureCraft-1.7.1-mc1.10.2.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.1} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.6.jar) 
	UCHIJAAAA	arsmagica2{1.5.017} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-17b.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-17b.jar) 
	UCHIJAAAA	autopackager{1.6.3} [AutoPackager] (autopackager-1.6.3.jar) 
	UCHIJAAAA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHIJAAAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	betterbuilderswands{0.10.2} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.10.2.209+115b204.jar) 
	UCHIJAAAA	betterthanbunnies{1.10.2-1.1.0} [BetterThanBunnies] (BetterThanBunnies-1.10.2-1.1.0.jar) 
	UCHIJAAAA	BiblioCraft{2.2.1} [BiblioCraft] (BiblioCraft[v2.2.1][MC1.10.2].jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UCHIJAAAA	BloodMagic{1.10.2-2.1.7-76} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.7-76.jar) 
	UCHIJAAAA	BloodArsenal{1.10.2-2.0.1-17} [Blood Arsenal] (BloodArsenal-1.10.2-2.0.1-17.jar) 
	UCHIJAAAA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.6.233} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCHIJAAAA	brandonscore{2.1.4} [Brandon's Core] (BrandonsCore-1.10.2-2.1.4.92-universal.jar) 
	UCHIJAAAA	ceramics{1.10.2-1.1.5} [Ceramics] (Ceramics-1.10.2-1.1.5.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	ChestTransporter{2.5.9} [Chest Transporter] (ChestTransporter-1.10.2-2.5.9.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCHIJAAAA	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.8.12} [Chisel] (Chisel-MC1.10.2-0.0.8.12.jar) 
	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJAAAA	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	UCHIJAAAA	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UCHIJAAAA	clipboard{@VERSION@} [Clipboard] (Clipboard-1.10.2-1.1.1.jar) 
	UCHIJAAAA	cyclopscore{0.9.3} [Cyclops Core] (CyclopsCore-1.9.4-0.9.3.jar) 
	UCHIJAAAA	commoncapabilities{1.3.1} [CommonCapabilities] (CommonCapabilities-1.9.4-1.3.1.jar) 
	UCHIJAAAA	compactsolars{1.10.2-5.0.8.331} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.8.331-universal.jar) 
	UCHIJAAAA	controlling{1.0.4} [Controlling] (Controlling-1.0.4.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.39} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.39.jar) 
	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCHIJAAAA	MineTweaker3{3.0.24} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCHIJAAAA	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UCHIJAAAA	darkutils{1.1.7.111} [Dark Utilities] (DarkUtilities-1.10.2-1.1.7.111.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJAAAA	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJAAAA	forestry{5.2.17.368} [Forestry] (forestry_1.10.2-5.2.17.368.jar) 
	UCHIJAAAA	eleccore{1.7.409} [ElecCore] (ElecCore-1.10.2-1.7.409.jar) 
	UCHIJAAAA	EnderStorage{2.2.1.103} [EnderStorage] (EnderStorage-1.10.2-2.2.1.103-universal.jar) 
	UCHIJAAAA	OpenComputers{1.6.2.7} [OpenComputers] (OpenComputers-MC1.10.2-1.6.2.7.jar) 
	UCHIJAAAA	deepresonance{1.4.6} [DeepResonance] (deepresonance-1.1x-1.4.6.jar) 
	UCHIJAAAA	defaultoptions{6.1.5} [Default Options] (DefaultOptions_1.10.2-6.1.5.jar) 
	UCHIJAAAA	draconicevolution{2.0.8} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.8.177-universal.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.6.1} [Storage Drawers] (StorageDrawers-1.10.2-3.6.1.jar) 
	UCHIJAAAA	bitdrawers{0.36} [Drawers & Bits] (DrawersBits-1.10.2-0.36.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCHIJAAAA	embers{0.104} [Embers] (embers-0.104.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.1.179} [Ender IO] (EnderIO-1.10.2-3.1.179.jar) 
	UCHIJAAAA	engineersworkshop{1.2.0-1.10.2} [Engineer's Workshop] (EngineersWorkshop-1.2.0-1.10.2.jar) 
	UCHIJAAAA	valkyrielib{1.10.2-0.10.6} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.6.jar) 
	UCHIJAAAA	environmentaltech{1.10.2-0.10.6b} [Environmental Tech] (environmentaltech-1.10.2-0.10.6b.jar) 
	UCHIJAAAA	etlunar{1.10.2-0.10.6a} [ET Lunar] (etlunar-1.10.2-0.10.6a.jar) 
	UCHIJAAAA	evilcraft{0.10.20} [EvilCraft] (EvilCraft-1.10.2-0.10.20.jar) 
	UCHIJAAAA	zerocore{1.10.2-0.1.0.4} [Zero CORE] (zerocore-1.10.2-0.1.0.4.jar) 
	UCHIJAAAA	bigreactors{1.10.2-0.4.5.27} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.27.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHIJAAAA	theoneprobe{1.4.4} [The One Probe] (theoneprobe-1.1x-1.4.4.jar) 
	UCHIJAAAA	immersiveengineering{0.10-57} [Immersive Engineering] (ImmersiveEngineering-0.10-57.jar) 
	UCHIJAAAA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJAAAA	morebees{1.10.2-1.3.2} [More Bees] (morebees-1.10.2-1.3.2.jar) 
	UCHIJAAAA	exnihiloomnia{1.2.6} [Ex Nihilo Omnia] (exnihiloomnia-1.2.6.jar) 
	UCHIJAAAA	excompressum{2.0.97} [Ex Compressum] (ExCompressum_1.10.2-2.0.97.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.3.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJAAAA	sonarcore{3.2.5} [SonarCore] (SonarCore-1.10.2-3.2.5.jar) 
	UCHIJAAAA	fluxnetworks{1.1.7} [FluxNetworks] (FluxNetworks-1.10.2-1.1.7.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-beta2-anarchy.jar) 
	UCHIJAAAA	forgelin{1.4.0} [Forgelin] (Forgelin-1.4.0.jar) 
	UCHIJAAAA	forgemultipartcbe{2.0.0.29} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.29-universal.jar) 
	UCHIJAAAA	microblockcbe{2.0.0.29} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.29-universal.jar) 
	UCHIJAAAA	minecraftmultipartcbe{2.0.0.29} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.29-universal.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.4.4.jar) 
	UCHIJAAAA	ftbtweaks{2.0.0} [FTB Tweaks] (FTBTweaks-2.0.0.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.4.3.jar) 
	UCHIJAAAA	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.10.2-alpha-0.0.3.jar) 
	UCHIJAAAA	Funnels{1.1.2} [Funnels] (Funnels-1.10.2-1.1.2.jar) 
	UCHIJAAAA	gendustry{1.6.5.30} [GenDustry] (gendustry-1.6.5.30-mc1.10.2.jar) 
	UCHIJAAAA	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCHIJAAAA	gravisuite{3.0.1} [Gravitation Suite] (Gravitation Suite-3.0.1.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	gregtech{MC1.10.2} [GregTech] (gregtech-5.10.40.jar) 
	UCHIJAAAA	hammercore{1.2.3} [Hammer Core] (HammerCore_1.10.2-1.2.3.jar) 
	UCHIJAAAA	helpfixer{1.0} [HelpFixer] (HelpFixer-1.10.2-1.4.15.jar) 
	UCHIJAAAA	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCHIJAAAA	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.38} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.38-universal.jar) 
	UCHIJAAAA	InGameInfoXML{2.8.1.89} [InGame Info XML] (InGameInfoXML-1.10.2-2.8.1.89-universal.jar) 
	UCHIJAAAA	integrateddynamics{0.6.10} [Integrated Dynamics] (IntegratedDynamics-1.10.2-0.6.10.jar) 
	UCHIJAAAA	integratedtunnels{1.1.0} [Integrated Tunnels] (IntegratedTunnels-1.10.2-1.1.0.jar) 
	UCHIJAAAA	intwheel{1.2.4} [Interaction Wheel] (intwheel-1.1x-1.2.4.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.23} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.23.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.10.2.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAA	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
	UCHIJAAAA	launchgui{@VERSION@} [LaunchGUI] (LaunchGui-1.9.4-2.0.3-23-client.jar) 
	UCHIJAAAA	boots{1.0} [Long Fall Boots] (LongFallBoots - Hard Mode.jar) 
	UCHIJAAAA	lootbags{2.3.2} [Loot Bags] (LootBags-1.10.2-2.3.2.jar) 
	UCHIJAAAA	mercurius{1.0.1} [Mercurius] (Mercurius-1.10.2-1.0.2.jar) 
	UCHIJAAAA	modularforcefieldsystem{2.5.0} [Modular ForceField System] (MFFS-1.10.2-3.0.0.0_1.10_655de1f.jar) 
	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJAAAA	mob_grinding_utils{0.1.8.16} [mob_grinding_utils] (MobGrindingUtils-0.1.8.16.jar) 
	UCHIJAAAA	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-1.0.1.jar) 
	UCHIJAAAA	modtweaker{2.0.10} [Mod Tweaker] (ModTweaker2-2.0.10.jar) 
	UCHIJAAAA	moreoverlays{1.10} [MoreOverlays] (moreoverlays-1.10-mc1.10.2.jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UCHIJAAAA	mputils{1.2.5} [ModPack Utilities] (mputils-1.10.2-1.2.5.jar) 
	UCHIJAAAA	mpbasic{1.1.3} [ModPack Basic Tools] (mpbasic-1.10.2-1.1.5.jar) 
	UCHIJAAAA	MrTJPCoreMod{2.0.0.14} [MrTJPCore] (MrTJPCore-1.10.2-2.0.0.14-universal.jar) 
	UCHIJAAAA	shetiphiancore{3.3.8} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.8.jar) 
	UCHIJAAAA	multistorage{1.2.15} [Multi-Storage] (multistorage-1.10.0-1.2.15.jar) 
	UCHIJAAAA	mysticalagriculture{1.4.4} [Mystical Agriculture] (mysticalagriculture[1.10.2]-1.4.4a.jar) 
	UCHIJAAAA	natura{1.10.2-4.1.0.24} [Natura] (natura-1.10.2-4.1.0.24.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJAAAA	openglider{@VERSION@} [Open Glider] (OpenGlider-1.10.2-0.2.2.jar) 
	UCHIJAAAA	p455w0rdslib{1.0.13} [p455w0rd's Library] (p455w0rdslib-1.10.2-1.0.13.jar) 
	UCHIJAAAA	projectred-core{4.8.1.25} [ProjectRed Core] (ProjectRed-1.10.2-4.8.1.25-Base.jar) 
	UCHIJAAAA	projectred-exploration{4.8.1.25} [ProjectRed Exploration] (ProjectRed-1.10.2-4.8.1.25-world.jar) 
	UCHIJAAAA	thermalfoundation{2.0.3} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.3.77-universal.jar) 
	UCHIJAAAA	plustic{3.1} [PlusTiC] (plustic-3.1.jar) 
	UCHIJAAAA	projectred-integration{4.8.1.25} [ProjectRed integration] (ProjectRed-1.10.2-4.8.1.25-integration.jar) 
	UCHIJAAAA	projectred-transmission{4.8.1.25} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.1.25-integration.jar) 
	UCHIJAAAA	projectred-illumination{4.8.1.25} [ProjectRed Illumination] (ProjectRed-1.10.2-4.8.1.25-lighting.jar) 
	UCHIJAAAA	projectred-expansion{4.8.1.25} [ProjectRed Expansion] (ProjectRed-1.10.2-4.8.1.25-mechanical.jar) 
	UCHIJAAAA	projectred-tansportation{1.0} [projectred-tansportation] (ProjectRed-1.10.2-4.8.1.25-mechanical.jar) 
	UCHIJAAAA	reborncore{2.13.5.136} [RebornCore] (RebornCore-1.10.2-2.13.5.136-universal.jar) 
	UCHIJAAAA	quantumstorage{3.2.19} [QuantumStorage] (QuantumStorage-1.10.2-3.2.19.jar) 
	UCHIJAAAA	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UCHIJAAAA	reauth{3.4.1} [ReAuth] (ReAuth-1.10-3.4.1.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.5.136} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.13.5.136-universal.jar) 
	UCHIJAAAA	reccomplex{1.2.9.1-1.10} [Recurrent Complex] (RecurrentComplex-1.2.9.1-1.10.jar) 
	UCHIJAAAA	redstonearsenal{2.0.2} [Redstone Arsenal] (RedstoneArsenal-1.10.2-2.0.2.27-universal.jar) 
	UCHIJAAAA	refinedrelocation{@VERSION@} [Refined Relocation] (RefinedRelocation-mc1.10.2-2.1.18.jar) 
	UCHIJAAAA	refinedstorage{1.2.23} [Refined Storage] (refinedstorage-1.2.23.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.639} [Reliquary] (Reliquary-1.10.2-1.3.3.639.jar) 
	UCHIJAAAA	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJAAAA	rftools{5.90} [RFTools] (rftools-1.1x-5.90.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCHIJAAAA	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHIJAAAA	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHIJAAAA	Signals{1.0} [Signals] (Signals-1.10.2-0.5.1-universal.jar) 
	UCHIJAAAA	SimilsaxTranstructors{1.10.2.18} [Similsax Transtructors] (SimilsaxTranstructors-1.10.2.18.jar) 
	UCHIJAAAA	simplevoidworld{1.1.0.4} [SimpleVoidWorld] (Simple-Void-World-1.10.2-1.1.0.4-universal.jar) 
	UCHIJAAAA	simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
	UCHIJAAAA	simplyjetpacks{2.0.3.26} [Simply Jetpacks 2] (SimplyJetpacks2-1.10.2-2.0.3.26.jar) 
	UCHIJAAAA	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
	UCHIJAAAA	snad{1.10.2-1.6.09.20a} [Snad] (Snad-1.10.2-1.6.09.20a.jar) 
	UCHIJAAAA	solarfluxreborn{2.13r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-2.13r.jar) 
	UCHIJAAAA	stevescarts{2.1.4.83} [Steve's Carts 2] (StevesCarts-1.10.2-2.1.4.83.jar) 
	UCHIJAAAA	storagedrawersextra{1.10-1.1.0} [Storage Drawers Extras] (StorageDrawersExtras-1.10-1.1.0.jar) 
	UCHIJAAAA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHIJAAAA	supercraftingframe{1.2.1.88} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.1.88.jar) 
	UCHIJAAAA	techreborn{2.1.10.207} [TechReborn] (TechReborn-1.10.2-2.1.10.207-universal.jar) 
	UCHIJAAAA	thebetweenlands{2.0.2-alpha} [The Betweenlands] (TheBetweenlands-2.0.2-alpha-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.0.3} [Thermal Expansion] (ThermalExpansion-1.10.2-5.0.3.86-universal.jar) 
	UCHIJAAAA	TinkersAddons{1.0.4} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.4.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	tp{1.1.0} [Tiny Progressions] (tinyprogressions-1.10.2-1.1.0.jar) 
	UCHIJAAAA	topaddons{1.10.2-0.9.1c} [TOP Addons] (topaddons-1.10.2-0.9.1c.jar) 
	UCHIJAAAA	torchmaster{1.0} [TorchMaster] (torchmaster_1.10.2-1.1.0.11.jar) 
	UCHIJAAAA	Translocator{2.1.3.52} [Translocator] (Translocators-1.10.2-2.1.3.52-universal.jar) 
	UCHIJAAAA	usefulnullifiers{1.3.4} [Useful Nullifiers] (usefulnullifiers-1.3.4.jar) 
	UCHIJAAAA	wanionlib{1.10.2-1.3} [WanionLib] (WanionLib-1.10.2-1.3.jar) 
	UCHIJAAAA	wcg{1.0.0} [Wireless Crafting Grid] (WirelessCraftingGrid-1.10.2-1.0.0.jar) 
	UCHIJAAAA	wct{0.0.17} [Wireless Crafting Terminal] (WirelessCraftingTerminal-1.10.2-0.0.17.jar) 
	UCHIJAAAA	Woot{1.10.2-1.2.6} [Woot] (woot-1.10.2-1.2.6.jar) 
	UCHIJAAAA	wrcbe{2.0.0} [WirelessRedstone-CBE] (WR-CBE-1.10.2-2.0.0.18-universal.jar) 
	UCHIJAAAA	xnet{1.1.2} [XNet] (xnet-1.1.2.jar) 
	UCHIJAAAA	xtones{1.10.2-1.0.1-3} [Xtones] (Xtones-1.10.2-1.0.1-3.jar) 
	UCHIJAAAA	yabba{1.10.2-0.3.0} [YABBA] (YABBA-1.10.2-0.4.0.jar) 
	UCHIJAAAA	unidict{1.10.2-2.7} [UniDict] (UniDict-1.10.2-2.7.jar) 
	Loaded coremods (and transformers): 
Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.2.1-1.10.jar)
  
ForgelinPlugin (Forgelin-1.4.0.jar)
  
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
IC2core (industrialcraft-2-2.6.142-ex110.jar)
  
CorePlugin (MrTJPCore-1.10.2-2.0.0.14-universal.jar)
  
TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  li.cil.oc.common.asm.ClassTransformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.0.155-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.2-alpha-universal.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  team.chisel.common.asm.ChiselTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.201-universal.jar)
  codechicken.nei.asm.NEITransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  
Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
SFRCore (SolarFluxReborn_1.10.2-2.13r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-17b.jar)
  am2.asm.Transformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
RebornCoreASM (RebornCore-1.10.2-2.13.5.136-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  appeng.coremod.transformer.ASMIntegration
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.8.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv4-alpha-11 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	NotEnoughItems Invalid Fingerprint Reports: 
	List of loaded APIs: 
		* actuallyadditionsapi (29) from ActuallyAdditions-1.10.2-r105.jar
		* AgriCraftAPI (1.0) from agricraft-2.0.0-0.7.0-a12.jar
		* appliedenergistics2|API (rv4) from appliedenergistics2-rv4-alpha-11.jar
		* Baubles|API (1.3.1.3) from Baubles-1.10.2-1.3.9.jar
		* BetweenlandsAPI (1.1.0) from TheBetweenlands-2.0.2-alpha-universal.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.10.2-0.4.5.27.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.10.2-2.1.7-76.jar
		* BotaniaAPI (85) from Botania r1.9-341.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.10.2-0.0.8.12.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.10.2-0.0.8.12.jar
		* ChiselsAndBitsAPI (12.10.0) from chiselsandbits-12.12.jar
		* CoFHAPI (1.8.9R1.2.0B1) from SimplyJetpacks2-1.10.2-2.0.3.26.jar
		* cofhapi (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhapi|block (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* cofhapi|core (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from plustic-3.1.jar
		* cofhapi|energy (1.4.0) from extrautils2-1.10.2-1.3.3.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.6.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from plustic-3.1.jar
		* cofhapi|item (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* cofhapi|tileentity (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* cofhapi|util (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|audio (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|gui (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|gui|container (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|gui|element (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|gui|element|listbox (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|gui|slot (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|inventory (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|util (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|util|helpers (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|world (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|world|feature (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.9.4-1.3.1.jar
		* compatlayer (0.2.5) from compatlayer-1.10-0.2.5.jar
		* ComputerCraft|API (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|FileSystem (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Lua (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Media (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Peripheral (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Permissions (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Redstone (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Turtle (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* CSLib|API (0.3.0) from Decocraft-2.3.6.1_1.10.2.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.6.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.10.2-2.0.8.177-universal.jar
		* ElecCoreAPI (1.0) from ElecCore-1.10.2-1.7.409.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.10.2-1.7.409.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.1.179.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.1.179.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.1.179.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.1.179.jar
		* environmentaltech-api (1.10.2-0.10.6b) from environmentaltech-1.10.2-0.10.6b.jar
		* ExCompressum|API (1.0) from ExCompressum_1.10.2-2.0.97.jar
		* fluxapi (1.0) from FluxNetworks-1.10.2-1.1.7.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|core (5.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.17.368.jar
		* funkylocomotion_api (2.0) from funky-locomotion-1.10.2-alpha-0.0.3.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.30-mc1.10.2.jar
		* Guide-API|API (1.10.2-2.0.3-46) from Guide-API-1.10.2-2.0.3-46.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-57.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-57.jar
		* integrateddynamics|api (0.2.0) from IntegratedDynamics-1.10.2-0.6.10.jar
		* intwheel_api (1.2.4) from intwheel-1.1x-1.2.4.jar
		* IronBackpacks|API (0.5) from IronBackpacks-1.10.2-2.2.23.jar
		* jeresources|API (0.5.8.98) from JustEnoughResources-1.10.2-0.5.8.98.jar
		* journeymap|client-api (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-display (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-event (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-model (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-util (1.3) from journeymap-1.10.2-5.4.6.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.14.7.416.jar
		* mcjtylib_ng (2.3.11) from mcjtylib-1.1x-2.3.11.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.10.2.jar
		* Open Glider|API (0.1) from OpenGlider-1.10.2-0.2.2.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.2.7.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.10.2-1.0.13.jar
		* PsiAPI (2) from Psi-r1.0-42.jar
		* railcraft:API|core (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|bore (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|carts (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|charge (3.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|crafting (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|events (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|fuel (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|helpers (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|items (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|locomotive (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|signals (3.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|tracks (3.0.0) from Railcraft_1.10.2-10.0.1.jar
		* reborncoreAPI (2.13.5.136) from RebornCore-1.10.2-2.13.5.136-universal.jar
		* reborncoreAPI|Fuel (2.13.5.136) from RebornCore-1.10.2-2.13.5.136-universal.jar
		* reborncoreAPI|Power (2.13.5.136) from RebornCore-1.10.2-2.13.5.136-universal.jar
		* reborncoreAPI|Recipe (2.13.5.136) from RebornCore-1.10.2-2.13.5.136-universal.jar
		* reborncoreAPI|Tile (2.13.5.136) from RebornCore-1.10.2-2.13.5.136-universal.jar
		* RefinedRelocationAPI (2.0.0) from RefinedRelocation-mc1.10.2-2.1.18.jar
		* stevescartsAPI (2.1.4.83) from StevesCarts-1.10.2-2.1.4.83.jar
		* stevescartsAPI|FARMS (2.1.4.83) from StevesCarts-1.10.2-2.1.4.83.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.2.23.jar
		* StorageDrawersAPI|inventory (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.2.23.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.2.23.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.2.23.jar
		* techrebornAPI (2.1.10.207) from TechReborn-1.10.2-2.1.10.207-universal.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.1x-1.4.4.jar
		* valkyrielib.api (1.10.2-0.10.6) from valkyrielib-1.10.2-0.10.6.jar
		* wct|API (1.10.2-rv4-1.0.0b) from WirelessCraftingTerminal-1.10.2-0.0.17.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.4.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.4.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.4.jar
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	ChickenChunks Invalid Fingerprint Reports: 
	EnderStorage Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * An unsupportted RF API is installed (1.7.10R1.3.1 from (guessing) jar:file:/home/manuel/ftb/FTBBeyond/minecraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/CoFHAPIProps.class).
                    Ender IO needs at least 1.4.0 and will NOT work with older versions.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/home/manuel/ftb/FTBBeyond/minecraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/home/manuel/ftb/FTBBeyond/minecraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/home/manuel/ftb/FTBBeyond/minecraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/home/manuel/ftb/FTBBeyond/minecraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/home/manuel/ftb/FTBBeyond/minecraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/home/manuel/ftb/FTBBeyond/minecraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/home/manuel/ftb/FTBBeyond/minecraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/home/manuel/ftb/FTBBeyond/minecraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/manuel/ftb/FTBBeyond/minecraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.5.136
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
	Translocator Invalid Fingerprint Reports: 
	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by SiblisCu** [comment]
This doesn't happen as soon you use the builder star working, It almost finished with e chunk before started crashing.

**Comment by Dyonovan** [comment]
Happens with any quarry. Seems to be a specific block.

**Comment by Exidex** [comment]
I fixed it, but it would be great to know what block exactly causes this crash, it might be different bug in worldgeneration. It is 100% small ore and you will get same crash when break it by hand

**Comment by Dyonovan** [comment]
I've got a cloned copy of the repo were I added that fix myself. I will add a debug line to it to find out which block is causing it.

**Comment by SiblisCu** [comment]
Still happens in 5.10.41. [Crash log.](https://pastebin.com/3apQKnRq)

The block that generates the crash is in "y" level 6 or below (if I'm not mistaken).

**Comment by SiblisCu** [comment]
I mined manually everything in that chunk from "y" level 7 to 1 (after this the crash didn't happen) this is what I found:

--- Mod: Gregtech.
- Black granite.
- Small sulfur ore.
- Small deep iron ore (dropped nothing, my money is in this one).

--- Mod: Thermal foundation.
- Nickel ore.
- Silver ore.

--- Mod: Tech reborn.
- Garnierite ore.

--- Mod: Project red.
- Electrotine ore.

--- Mod: Chisel.
- Bassalt (raw)

--- "Mod": Minecraft
- Coal ore
- Iron ore
- Gold ore
- Redstone ore
- Stone
- Gravel
- Granite
- Lava
- Bedrock

I hope this info is useful.

**Comment by Exidex** [comment]
Build wasn't updated since when PR was merged. I tested it on small amber ore and it was crashing because it has nothing to drop. The different question though is why small amber ore is generated in world when Thaumcraft is not present.

**Comment by SiblisCu** [comment]
I think adding or removing mods to a pack can change the type of already generated ores. If the table of materials is changed by this it can happen that material number x is another thing after the modification of the pack and the material that was x now has another number.
